/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanSearch: typeof import('vant/es')['Search']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanButton: typeof import('vant/es')['Button']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanSearch: typeof import('vant/es')['Search']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
}